version: "3.10"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: uvicorn app.api:app --host 0.0.0.0 --port 80
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"